services:
  app:
    image: node:16
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    working_dir: /app
    env_file:
      - '.env'
    command: yarn dev:api
    depends_on:
      - redis
      - mongodb
      - worker

  worker:
    image: node:16
    volumes:
      - ./:/app
    working_dir: /app
    env_file:
      - '.env'
    command: yarn dev:worker
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis
    ports:
      - 6379:6379

  mongodb:
    image: mongo:4.4
    ports:
      - 27017:27017
