export enum ErpFulfillmentStatusEnum {
  PENDING = 'PENDING',
  WAITING = 'WAITING',
  PICKING = 'PICKING',
  CHECKED = 'CHECKED',
  BILLING = 'BILLING',
  BILLING_CONFIRMATION = 'BILLING_CONFIRMATION',
  INVOICED = 'INVOICED',
  SHIPPED = 'SHIPPED',
  PICKUP_READY = 'PICKUP_READY',
  DELIVERED = 'DELIVERED',
  CANCELED = 'CANCELLED'
}
